### ISSUE TITLE
Sounds awful over RDP

### ISSUE THREAD

**Issue by thomasrayner** [steviecoaster/PSChristmasCarols#1] opened 2018-12-17 18:18 UTC
Trying to play Christmas carols on a computer that you are connected to via RDP results in a poor audio experience. It sounds static-y, is choppy, and otherwise un-Christmas-y. It certainly impacts my holiday spirit.

**Steps to reproduce**
1. Run `mstsc.exe`
2. Connect to another computer, ensuring that audio will be passed through to your workstation
3. Run the following

```powershell
. .\Resolve-Note.ps1
$data = gc .\JingleBells.json | ConvertFrom-Json
$data | Resolve-Note
```

4. Listen and try to enjoy the music despite it's degraded audio quality.

**Comment by corbob** [comment] 2018-12-17 18:20
Listening to audio over RDP is a poor experience to begin with. This feels out of scope for this project. You should probably file a  bug with Microsoft.

**Comment by DWSR** [comment] 2018-12-17 18:21
Can't reproduce. #worksforme

**Comment by thomasrayner** [comment] 2018-12-17 18:22
> Listening to audio over RDP is a poor experience to begin with. This feels out of scope for this project. You should probably file a bug with Microsoft.

@corbob I think you may need to wait for Windows to go open source for that.

**Comment by steviecoaster** [comment] 2018-12-17 18:44
Just.....no.

**Closed as completed by steviecoaster** 2018-12-17 18:44 UTC
Labels: wontfix
